jdbc:
  dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  url: jdbc:mysql://127.0.0.1:3306/microflow
  useUnicode: true
  charaterEncoding: utf8
  databaseName: microflow
  serverName: 127.0.0.1
  username: root
  password: root
  cachePrepStmts: true
  prepStmtsSize: 250
  prepStmtsCacheSqlLimit: 2048
  userServerPrepStmts: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
logging:
  path: ./logs
  file: microflow.log
  level:
    org.springframework.transaction: TRACE
    com.ibatis: DEBUG
com.baidu.microflow.generator.bashFileParentPath: /home/work/wangxiaoxi/
#script.file.max.in.memory.size: 400KB
