val t1 = new QETask("1 task")
val t2 = new QETask("2 task")
val t3 = new QETask("3 task")
val t4 = new BashTask("4 task")
val t5 = new BashTask("5 task")
val t6 = new BashTask("6 task")
val t7 = new BashTask("7 task")


t1.hql("SELECT * FROM tbl_one")
t1.param("--sessionconf engine=wing location=PINGO")
t2.hql("SELECT * FROM tbl_two")
t2.param("--sessionconf engine=wing location=PINGO")
t3.hql("SELECT * FROM tbl_three")
t3.param("--sessionconf engine=wing location=PINGO")
t4.bash("bash /Users/eddix/run.sh")
t5.bash("date")
t6.bash("ls")
t7.bash("date")

job.addTask(t1)
job.addTask(t2)
job.addTask(t3)
job.addTask(t4, Set(t1, t2))
job.addTask(t5, Set(t2, t3))
job.addTask(t6, Set(t4, t5))
job.addTask(t7, t6)
